### ISSUE TITLE
When instantly loading a save, the assets are not loading correctly.

### ISSUE THREAD

**Issue by Programmer-Timmy** [CitiesSkylinesModding/CS2-AssetPacksManager#10]
## What is the issue
When instantly loading a save, the assets are not loading correctly, which results in missing textures or objects in the game.

## When does the issue appear?
The issue appears immediately upon loading a save file. Assets that were previously available and correctly displayed are missing or not rendered properly.

## Have you used the `Delete Mods Cache`-Option in Asset Packs Manager? If not, why not?
No, It should not have an effect on this issue.

## Have you deleted the `C:/Users/%username%/AppData/LocalLow/Colossal Order/Cities Skylines II/Mods` folder? If not, why not?
No, I have not deleted this folder. It should not have an effect on this issue.

## Have you deleted the `C:/Users/%username%/AppData/LocalLow/Colossal Order/Cities Skylines II/CustomAssets` folder? If not, why not?
No, I have not deleted this folder. It should not have an effect on this issue.

**Comment by Mimonsi** [comment]
This is working as designed, you need to wait in the main menu until all assets are loaded. 

I have a version in progress that prohibits loading a save until all mods have finished initializing.

**Comment by Programmer-Timmy** [comment]
Thank you for the update. I reported this issue because the current design—requiring users to wait in the main menu until all assets are loaded—feels a bit cumbersome. Since this mod is already in a full release, I think addressing usability concerns like this would be beneficial for the user experience. It might be worth considering making improvements in future updates to enhance how users interact with the mod. I appreciate your ongoing work.

**Comment by Mimonsi** [comment]
The alternatives would be an increased wait-time before the main menu even opens. There are no other options. Earlier versions did all the loading before the main menu even showed, but now it can be done in the background and the user can see the progress.

**Comment by Programmer-Timmy** [comment]
Alright, but that could still be possible. You could implement a check when loading a city so that if not all elements are loaded, the save game doesn't complete loading. Thanks for your work, though. This is just an idea. (From what i have learned, this should be possible)
