### ISSUE TITLE
Crash while load save

### ISSUE THREAD

**Issue by O1dDing** [CitiesSkylinesModding/CS2-AssetPacksManager#11]
## What is the issue
Game crash

## When does the issue appear?
While load a savefile

## Have you used the `Delete Mods Cache`-Option in Asset Packs Manager? If not, why not?
Yes, but still the same.

## Have you deleted the `C:/Users/%username%/AppData/LocalLow/Colossal Order/Cities Skylines II/Mods` folder? If not, why not?
No, but, it shall result as same as previous term.

## Have you deleted the `C:/Users/%username%/AppData/LocalLow/Colossal Order/Cities Skylines II/CustomAssets` folder? If not, why not?
No, but, it shall result as same as previous term.

## Attached Logs from `C:/Users/%username%/AppData/LocalLow/Colossal Order/Cities Skylines II/Logs`
[AssetPacksManager.Mod.log](https://github.com/user-attachments/files/17165677/AssetPacksManager.Mod.log)

FYI: Create a new game save (the "new game" option ) is working functional, but loading previous save (the "load game" ) will crash after click load (depend on how many mod that you install, if too much will take a couple seconds to crash)

**Comment by O1dDing** [comment]
Game version 1.1.8f1, AMP version 1.4.2

**Comment by Mimonsi** [comment]
Thanks for the report. Please test if the issue still occurs when only using APM and asset packs, and no other mods (beside I18N Everywhere)

**Comment by O1dDing** [comment]
> Thanks for the report. Please test if the issue still occurs when only using APM and asset packs, and no other mods (beside I18N Everywhere)

it still crash, the logs of game tells the same thing saying missing "ElectricityFlowEdge for connected node"
Still, you can open a new game but cannot load game
Beside that, when you creating a new playset with APM and set to active (2 playset with APM), the next time will instantly crash when you open paradox mod platform (In game), but I don't think this is caused by the APM due to the logs.

Part of logs:
[info.txt](https://github.com/user-attachments/files/17167298/info.txt) (the crash when open mod platform)
[info-2.txt](https://github.com/user-attachments/files/17167318/info-2.txt) (the crash only with APM while load saves)

**Comment by O1dDing** [comment]
find out what the problem is, the problem is caused by "anarchy", but anyway thx for the assist.
