### ISSUE TITLE
Missing CID Problems

### ISSUE THREAD

**Issue by CodingMoeButa** [CitiesSkylinesModding/CS2-AssetPacksManager#3]
I find that once the actived playlist changed or asset mods disabled, the game will delete all *.prefab.cid files in the mods' assets folder, then cause missing CID problems. Do you have any idea about it?

Now we can clear mods' cache and restart the game to redownload asset mods to solve it temporarily, but all mods should be redownload and it's very troublesome. I suggest that we can only clear asset mods' cache, excepting other mods.

Or do we have some methods to prevent the game from deleting *.prefab.cid files?

**Comment by Mimonsi** [comment]
Thank you for the suggestion. I already tried to reproduce it like you explained it, but I don't get the missing cids. I also couldn't figure out why this would happen.

I am currently working on the "selective cache clearing" you described. It will probably be released in a few days, close to the Custom Asset Pack Update

**Comment by Mimonsi** [comment]
An even better fix for this issue will be Released in 1.1.0. It includes a backup mechanic for the CID files.

**Comment by Mimonsi** [comment]
Issue has been resolved with Version 1.1.0

**Comment by CodingMoeButa** [comment]
Thanks for your work.
