### ISSUE TITLE
Always Open FIRE & RESCUE Panel Automatically

### ISSUE THREAD

**Issue by CodingMoeButa** [CitiesSkylinesModding/CS2-AssetPacksManager#4]
This happens whenever select an asset loaded by AssetPacksManager, not related to specific asset mods.

![屏幕截图 2024-05-02 160047](https://github.com/kosch104/CS2-AssetPacksManager/assets/20151731/0bae7af5-8f10-4125-8e42-1d19fccdae53)

**Comment by Mimonsi** [comment]
I am aware of this issue but currently have no idea what might be causing this. Thanks for the report.

**Comment by Mimonsi** [comment]
Doesn't happen anymore when adaptive loading is enabled
