### ISSUE TITLE
Legacy CustomAssets folder migration not working with OneDrive

### ISSUE THREAD

**Issue by Mimonsi** [CitiesSkylinesModding/CS2-AssetPacksManager#5]
When using OneDrive the Desktop path is not `C:/Users/[USER]/Desktop`, so moving the custom assets file does not work.

**Comment by CodingMoeButa** [comment]
Funny. How did you relate it to OneDrive?

**Comment by Mimonsi** [comment]
> Funny. How did you relate it to OneDrive?

It actually got found out while testing a beta version of the Custom Asset Pack repository. Apparently there is a OneDrive setting that changes the Desktop path, so the C:/Users/[USER]/Desktop path does not exist, or throws an "access denied" exception. I built the function to fail silently without any logs or errors, because I thought there was nothing to go wrong and error logs about uncommunicated functionality would be annoying at best... but I hope everything works now. By now, everybody who had used CustomAssets before the Rework should also have solved these problems anyway and the folder should be gone for most people.
