### ISSUE TITLE
Error message on start

### ISSUE THREAD

**Issue by Skryl0n** [CitiesSkylinesModding/CS2-AssetPacksManager#6]
## When does the issue appear?
At launch, when the menu appears (New Game, Load, etc.)

## Have you used the `Delete Mods Cache`-Option in Asset Packs Manager? If not, why not?
yes

## Have you deleted the `C:/Users/USERNAME/AppData/LocalLow/Colossal Order/Cities Skylines II/Mods` folder?
No

## Have you deleted the `C:/Users/USERNAME/AppData/LocalLow/Colossal Order/Cities Skylines II/CustomAssets` folder?
No

## What is the issue
I get this message error:

## When does the issue appear?
At launch, when the menu appears (New Game, Load, etc.) and having trouble pinpointing which asset might be causing

[object Object]
NullReferenceException: Object reference not set to an instance of an object
  at Colossal.IO.AssetDatabase.PrefabAsset+PrefabReferenceResolver.TryResolveReference (System.String id, System.Object& value) [0x00052] in <fe1d2d18769949e7903cf7eb3c357d2b>:0 
  at Colossal.OdinSerializer.DeserializationContext.GetExternalObject (System.String id) [0x00033] in <d9cab27576e9499db8aa70c41ecc0a40>:0 
  at Colossal.OdinSerializer.AnySerializer.ReadValueWeak (Colossal.OdinSerializer.IDataReader reader) [0x006df] in <d9cab27576e9499db8aa70c41ecc0a40>:0 
  at Colossal.OdinSerializer.ReflectionFormatter`1[T].DeserializeImplementation (T& value, Colossal.OdinSerializer.IDataReader reader) [0x0013d] in <d9cab27576e9499db8aa70c41ecc0a40>:0 
Colossal.Logging.CustomLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
Colossal.OdinSerializer.CustomLogger:LogException(Exception)
Colossal.OdinSerializer.DebugContext:LogException(Exception)
Colossal.OdinSerializer.ReflectionFormatter`1:DeserializeImplementation(BrandObject&, IDataReader)
Colossal.OdinSerializer.BaseFormatter`1:Deserialize(IDataReader)
Colossal.OdinSerializer.BaseFormatter`1:Colossal.OdinSerializer.IFormatter.Deserialize(IDataReader)
Colossal.OdinSerializer.ComplexTypeSerializer`1:ReadValue(IDataReader)
Colossal.OdinSerializer.ListFormatter`1:DeserializeImplementation(List`1&, IDataReader)
Colossal.OdinSerializer.BaseFormatter`1:Deserialize(IDataReader)
Colossal.OdinSerializer.BaseFormatter`1:Colossal.OdinSerializer.IFormatter.Deserialize(IDataReader)
Colossal.OdinSerializer.AnySerializer:ReadValueWeak(IDataReader)
Colossal.OdinSerializer.ReflectionFormatter`1:DeserializeImplementation(BuildingPrefab&, IDataReader)
Colossal.OdinSerializer.BaseFormatter`1:Deserialize(IDataReader)
Colossal.OdinSerializer.BaseFormatter`1:Colossal.OdinSerializer.IFormatter.Deserialize(IDataReader)
Colossal.OdinSerializer.AnySerializer:ReadValueWeak(IDataReader)
Colossal.OdinSerializer.SerializationUtility:DeserializeValueWeak(IDataReader)
Colossal.OdinSerializer.SerializationUtility:DeserializeValueWeak(Stream, DataFormat, DeserializationContext)
Colossal.IO.AssetDatabase.PrefabAsset:Load()
AssetPacksManager.Mod:LoadAssets(Dictionary`2) (at C:\Users\Konsi\RiderProjects\CS2-AssetPacksManager\Mod.cs:258)
AssetPacksManager.Mod:LoadModAssets() (at C:\Users\Konsi\RiderProjects\CS2-AssetPacksManager\Mod.cs:420)
AssetPacksManager.Mod:LoadModAssetsInForeground() (at C:\Users\Konsi\RiderProjects\CS2-AssetPacksManager\Mod.cs:188)
AssetPacksManager.Mod:OnLoad(UpdateSystem) (at C:\Users\Konsi\RiderProjects\CS2-AssetPacksManager\Mod.cs:80)
Game.Modding.ModInfo:OnLoad(UpdateSystem)
Game.Modding.ModInfo:Load(UpdateSystem)
Game.Modding.ModManager:InitializeMods(UpdateSystem)
Game.Modding.ModManager:Initialize(UpdateSystem)
Game.SceneFlow.GameManager:InitializeModManager(Boolean)
Game.SceneFlow.<<RegisterPdxSdk>g__RegisterDatabase|9>d:MoveNext()
System.Runtime.CompilerServices.AsyncTaskMethodBuilder:Start(<<RegisterPdxSdk>g__RegisterDatabase|9>d&)
Game.SceneFlow.<>c__DisplayClass106_1:<RegisterPdxSdk>g__RegisterDatabase|9()
Game.SceneFlow.<<RegisterPdxSdk>b__4>d:MoveNext()
System.Runtime.CompilerServices.MoveNextRunner:InvokeMoveNext(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Runtime.CompilerServices.MoveNextRunner:Run()
System.Threading.Tasks.AwaitTaskContinuation:InvokeAction(Object)
System.Threading.Tasks.AwaitTaskContinuation:RunCallback(ContextCallback, Object, Task&)
System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation:Run(Task, Boolean)
System.Threading.Tasks.Task:FinishContinuations()
System.Threading.Tasks.Task:FinishStageThree()
System.Threading.Tasks.Task`1:TrySetResult(VoidTaskResult)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetResult(VoidTaskResult)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetResult(Task`1)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder:SetResult()
Colossal.PSI.PdxSdk.<SyncMods>d__152:MoveNext()
System.Runtime.CompilerServices.MoveNextRunner:InvokeMoveNext(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Runtime.CompilerServices.MoveNextRunner:Run()
System.Threading.Tasks.<>c:<.cctor>b__7_0(Object)
UnityEngine.WorkRequest:Invoke()
UnityEngine.UnitySynchronizationContext:Exec()
UnityEngine.UnitySynchronizationContext:ExecuteTasks()

**Comment by Mimonsi** [comment]
There was an update for mixed zoning mod, please re-check, if that solved the issue.

Please also delete The Mods and CustomAssets folder like it says in the template

**Comment by Skryl0n** [comment]
Thanks!

The update seems to have worked. Thank you!!
